### ISSUE TITLE
a few comments on the vignette

### ISSUE THREAD

**Issue by stephaniehicks** [christinehou11/HuBMAPR#13]
- Can we use a different variable name (rather than the name of the function)? e.g. in this line https://github.com/christinehou11/HuBMAPR/blob/9e7c46153536125607d4393e6431d279dccc4c18/vignettes/hubmapr_vignettes.Rmd#L66 can we use something like 

```
dset <- datasets()
```
- Can we add an "overview" section, in particular in the `pkgdown` website, where you talk about a bit about the technical details behind the API? I am sure many folks would be curious to know what packages you used or how it API works generally? 
- I'm not sure I understand, but I see certain columns (e.g. `Age` in the `donors()` tibble say `<chr>` type, but would it make more sense to convert to a numeric? Though I see you operating on it with greater than / equal. 
- which makes me wonder could we include a plot in the vignette? like could we make a histogram of the age across the donors? Just to showcase a little what you can do with the datasets? 

ok that's it for now. Still working through this vignette and might have additional comments soon! thanks Christine for your hard work on this!

**Comment by mtmorgan** [comment]
FWIW I think something like `dsets <- datasets()` is not really a best practice, especially if thinking about accessibility across languages, where one has to already translate 'datasets' into, e.g., Dutch, and then to also remember that `dsets` is a synonym for `datasets`.

**Comment by stephaniehicks** [comment]
That's a really great point @mtmorgan. What about `datasets_df <- datasets()`? Or maybe i'm over thinking it and it's not really a problem to begin with haha?

**Comment by christinehou11** [comment]
I added a plot to display datasets info!
Also change the name to be consistent.
